### ISSUE TITLE
XCM ROUTER: Resolve release conflicts

### ISSUE THREAD

**Issue by dudo50** [paraspell/xcm-tools#168]
Split release please manifest to 2 independent files to resolve conflicts between merging new versions.

This requires:
- Updating code

**Comment by michaeldev5** [comment]
Related issue that might help resolve the problem: https://github.com/googleapis/release-please/issues/1870#issuecomment-1748390833

**Comment by dudo50** [comment]
Resolved by further research:

1. The Autorelease pending tag must be removed and the latest Release please CI must be rerun.
The release please then regenerates release PR. It will no longer contain conflicts then.
