### ISSUE TITLE
support for custom chain config and assets

### ISSUE THREAD

**Issue by nuel77** [paraspell/xcm-tools#193]
Hello, 
In the current SDK, is there a way to set custom configuration for a particular chain?

For, example the SDK supports our para chain for direct transfers, but suppose we want the multilocation of transfer to be customized, so the the user can directly add funds to one of our exchange pallet accounts, is there a clean way to add this "configuration" to the SDK, without forking or having a local implementation on it.

This is kindof similar to how moonbeam-xcm-sdk supports a `configsService`  where you can provide your custom implementation for each of the parachains as required eg:

```js
import { ConfigService, ConfigBuilder } from "@moonbeam-network/xcm-config";

const configService = new ConfigService({
  assets: assetsMap,
  chains: chainsMap,
  chainsConfig: chainsConfigMap,
});

const sdkInstance = Sdk({ configService });
```

It would really nice have this, as then each parachain can easily use the SDK for chain specific needs. Would love to hear your thoughts on this.

**Comment by dudo50** [comment]
Sounds like brilliant idea! Added to the development pipeline. We will let you know once this will be added via ping.

With kind regards
Team ParaSpell

**Comment by nuel77** [comment]
Thanks for the prompt reply and actions. Look forward to this. Cheers 🥂

**Comment by dudo50** [comment]
Hey @nuel77 ! We are happy to inform you, that we have developed feature you wished SDK to have. Feel free to check it out in following PR: https://github.com/paraspell/xcm-tools/pull/199

We will merge it once you confirm, that the feature has everything you need it to have. You can now customize every possible multilocation (destination, address and currency). This means, that you can create fully custom XCM calls from now on.

Looking forward to your feedback.

With kind regards,
Team ParaSpell

**Comment by nuel77** [comment]
Wow, you guys are quick! This is exactly the feature I was looking for. Thanks!!

**Comment by dudo50** [comment]
Okay, merging and releasing soon. Will let you know once update is out and SDK is ready to be used with new feature. We will provide documentation to it for other devs soon.

With kind regards,
Team ParaSpell

**Comment by dudo50** [comment]
@nuel77 SDK is now ready to be used with new feature in version 5.1.0. Have fun exploring what it can achieve and let us know if you have any requests for functionality that can be helpful. 
https://github.com/paraspell/xcm-tools/pull/201
https://www.npmjs.com/package/@paraspell/sdk

With kind regards,
Team ParaSpell
