### ISSUE TITLE
Support for querying balances for parachains

### ISSUE THREAD

**Issue by ap211unitech** [paraspell/xcm-tools#204]
Hey guys, 

In the current version of SDK, is there a way to querying balances for a specific chain and asset ? Basically, before transferring asset to other chains, one need to check some base conditions like 

1. if user has enough amount to send over other network
2. estimated fee and fee token balance on source chain
3. estimated fee and fee token balance on destination chain 

Also, it could be great to get minimum transferrable amount and maximum tranferrable amount from directly from SDK itself. which is again dependent on balances and existential deposit.

For example, Moonbeam SDK provide a big object of transfer data which contains all these things in one place - 

<img width="835" alt="transfer_data" src="https://github.com/paraspell/xcm-tools/assets/65214523/10b1d099-86e3-4c4d-9420-2503dad93262">
<br></br>

This would be really helpful if it gives full transfer data. I'd be interested in hearing your opinions on this.

**Comment by dudo50** [comment]
Yes, this is good idea. We did not yet implement this because there were issues with existential deposits on Polkadot and Kusama > AssetHubs transfers. They are about to be fixed so we will add this to pipeline. Thanks for the suggestion @ap211unitech !

**Comment by dudo50** [comment]
Hey @ap211unitech, we are happy to inform you, that we have just implemented the feature you requested!

Here is PR: https://github.com/paraspell/xcm-tools/pull/234

Docs will follow soon after (There are plenty of new queries available to front-end developers now).

You can try it out on our [Playground](https://playground.paraspell.xyz/xcm-sdk-sandbox) in Transfer info section:
<img width="1193" alt="Snímka obrazovky 2024-05-24 o 13 18 19" src="https://github.com/paraspell/xcm-tools/assets/55763425/c76fced5-6547-4503-8ddb-87ca98e26f50">


The result will then be formatted in the following manner:
<img width="553" alt="Snímka obrazovky 2024-05-24 o 12 38 04" src="https://github.com/paraspell/xcm-tools/assets/55763425/865427cb-5a3f-4d5e-ba96-2d8009d6b7b5">
