### ISSUE TITLE
Deprecate Mangata?

### ISSUE THREAD

**Issue by vikiival** [paraspell/xcm-tools#259]
Hey, 
as Mangata is moving out of the Polkadot (it is called Gasp now).
I am thinking to remove `mangata`-related packages.

```
└─┬ @paraspell/sdk 5.5.0
  └─┬ @mangata-finance/type-definitions 2.1.2
    └── ✕ unmet peer @polkadot/types@^10.9.1: found 11.2.1
```

**Comment by dudo50** [comment]
Thanks for this suggestion. Indeed, we should remove the package. We used it for wallet signature as their chain required a specific config. This will be reviewed during the monthly maintenance check.
