### ISSUE TITLE
Consider migration towards PAPI

### ISSUE THREAD

**Issue by dudo50** [paraspell/xcm-tools#331]
As PAPI succeeds PJS libraries, consider migration towards PAPI.

This needs to be done carefully as many projects, that implement us currently also use PJS.

**Comment by Tbaut** [comment]
Hi there, papi is the way to go for future Dapps IMHO. I wouldn't build anything on polkadot-js/api today if I had to start a new app. I'd be interested in an xcm tool for papi if it was available. Thanks

**Comment by dudo50** [comment]
Hello @Tbaut , we are happy to inform you, that we are migrating to PAPI this month. It is second task in Pipeline so expect this issue to be resolved soon 🙂!

With kind regards,
Team ParaSpell✨

**Comment by dudo50** [comment]
@Tbaut , happy to inform you, that the full support for PAPI has just rolled out, we will update documentation today by EOD and package should be released within 2 days.

How will it work:
You install ParaSpell XCM SDK into your project
✨ You install package you wish to have (Either PJS or PAPI)
✅ XCM SDK automatically uses either PAPI or PJS (Whichever installed)
✅Functions are 1:1 so existing projects can switch just by reinstalling package from PJS to PAPI.

See commit: https://github.com/paraspell/xcm-tools/commit/b3a1e72f11d13b7f43f077bb2f68cb27903cc7cc

**Comment by Tbaut** [comment]
This is very very good, and also a very good timing.. because I need to do some XCM calls in Multix, that I'm almost done migrating to papi.. and this will allow me to test paraspell xcm tool!

**Comment by dudo50** [comment]
@Tbaut , feel free to contact me through telegram via "Dudo50" and I can assemble group ParaSpell<>Multix, and we can help you with the implementation or in case any issue arises.

With kind regards,
Dudo
