### ISSUE TITLE
Add more UX friendly error messages when passing incorrect address type to SDK

### ISSUE THREAD

**Issue by michaeldev5** [paraspell/xcm-tools#400]
When user enters a wrong account address type, for example if a node is EVM and user enters Polkadot address the error message is hard to understand where is the problem. Instead we should mark all EVM nodes and validate the address based on that.

**Comment by laalauren1** [comment]
> When user enters a wrong account address type, for example if a node is EVM and user enters Polkadot address the error message is hard to understand where is the problem. Instead we should mark all EVM nodes and validate the address based on that.

@michaeldev5 It seems like there's an issue with the error message clarity when entering the wrong account address type. To improve this, marking all EVM nodes and validating the address based on that can enhance user understanding. This way, users will receive clearer feedback if they input the wrong address type.
