### ISSUE TITLE
Setup more benevolent `peerDependencies` for SDK

### ISSUE THREAD

**Issue by vikiival** [paraspell/xcm-tools#410]
### Context

Observing `package.json` in XCM SDK I have found out that the rules for `peerDependencies` are pretty strict

### Solution

I would prefer to have more benevolent rules for packages
- https://github.com/kodadot/packages/pull/212

e.g:
current 

```json
  "peerDependencies": {
    "@polkadot/api": "^12.4.2",
    "@polkadot/api-base": "^12.4.2",
    "@polkadot/apps-config": "^0.143.2",
    "@polkadot/types": "^12.4.2",
    "@polkadot/util": "^13.0.2"
  }
```

ideal

```json
  "peerDependencies": {
    "@polkadot/api": ">= 12.4",
    "@polkadot/api-base": ">= 12.4",
    "@polkadot/apps-config": ">= 0.143",
    "@polkadot/types": ">= 12.4",
    "@polkadot/util": ">= 13"
  }
```

### Ref 

- https://nodejs.org/en/blog/npm/peer-dependencies

**Comment by dudo50** [comment]
@vikiival , added :). Thanks for the improvement suggestion!
