### ISSUE TITLE
Refactor transfer Builder to explicitly include from, to parameters for relaychains

### ISSUE THREAD

**Issue by michaeldev5** [paraspell/xcm-tools#472]
Currently, when a user wants to make a relay-to-para or para-to-relay transfer, they must omit the 'from' or 'to' parameter from the builder. Allowing the user to explicitly provide both 'from' and 'to' parameters would reduce code verbosity when using the builder efficiently in dApps

**Comment by dudo50** [comment]
In pipeline for early december

**Comment by dudo50** [comment]
Also include https://github.com/paraspell/xcm-tools/issues/531 and https://github.com/paraspell/xcm-tools/issues/528

**Comment by dudo50** [comment]
And https://github.com/paraspell/xcm-tools/issues/533
