### ISSUE TITLE
Solve the possibility of duplicated paraIds in function resolveTNodeFromMultiLocation

### ISSUE THREAD

**Issue by michaeldev5** [paraspell/xcm-tools#474]
Right now when creating a relay to para transfer and passing a multi-location destination, we are extracting para id from that multi location and based on that selecting a node class. That might not always work as polkadot and kusama ecosystem parachainsmay have duplicated paraIds. Solving issue #472 may also solve this issue.

**Comment by dudo50** [comment]
Resolved in refactore where `from` parameter now has to be always specified. So #472 resolved this issue.
