### ISSUE TITLE
Support for Multi-Hop XCM Transfers with @paraspell/sdk (via `transferAssetsUsingTypeAndThen`)

### ISSUE THREAD

**Issue by lrazovic** [paraspell/xcm-tools#512]
I'm looking to migrate from the Asset Transfers API to `@paraspell/sdk`, as it offers PAPI support, which aligns better with our requirements on Polimec.

In our setup, we use Asset Hub as the DOT reserve. This setup requires us to perform a `transferAssetsUsingTypeAndThen` on Polkadot, enabling a DOT transfer that flows from Polkadot to Asset Hub and finally to Polimec, all within a single extrinsic. This approach consolidates the process, optimizing for user experience.

Here is the current XCM message structure we use to accomplish this transfer:

[View XCM Message on Gist](https://gist.github.com/lrazovic/2e06bef4972ed6e2a61d1ea3ce143e70)

My question is whether it’s possible to construct this specific XCM message using the `@paraspell/sdk`. If multi-hop transfers (Polkadot → Asset Hub → Polimec) are supported or can be configured within the SDK, any guidance on setting this up would be highly appreciated. If not, are there any planned features that might enable this functionality?

Thank you for your help and for the ongoing development of Paraspell!

**Comment by dudo50** [comment]
Hey @lrazovic, first of all, thanks for considering our SDK! It means a lot to us!

As of right now, the `transferAssetsUsingTypeAndThen` extrinsics have to be manually added to each scenario, but we have structure and support for them as we already have few Parachains that use this extrinsic also (eg. Bifrost).

So it's just a matter of implementing support for this for the Polimec network as well. This support can be done within hours.

> any guidance on setting this up would be highly appreciated

We offer free support to any team implementing our SDK via 1<>1 telegram groups
Feel free to contact me on Telegram and we can guide you through your migration :).
Telegram handle: "Dudo50"

With kind regards,
Team ParaSpell

**Comment by dudo50** [comment]
Also add support for
Polimec <> AHP

- [ ] USDC
- [ ] USDT
- [ ] DOT

**Comment by dudo50** [comment]
Support for multihop Polimec <> Polkadot DOT transfers added, also added support for Polimec <> AHP USDC,USDT & DOT. This support will be in the next release scheduled within 2 days.
